# Generated by Django 5.1.7 on 2025-03-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_cuser_options_cuser_is_active_cuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuser',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cuser',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
