# Generated by Django 5.1.7 on 2025-03-31 20:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_otprequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otprequest',
            old_name='reciver',
            new_name='receiver',
        ),
        migrations.AlterField(
            model_name='otprequest',
            name='request_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
