# Generated by Django 5.1.7 on 2025-04-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_reciver_otprequest_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='password',
            field=models.CharField(default='1171', max_length=4),
        ),
    ]
