# Generated by Django 5.1.7 on 2025-04-01 09:09

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_otprequest_created_alter_otprequest_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='password',
            field=models.CharField(default='7707', max_length=4),
        ),
        migrations.AlterField(
            model_name='otprequest',
            name='receiver',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IR'),
        ),
    ]
