# Generated by Django 5.1.7 on 2025-04-27 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_otprequest_password_alter_otprequest_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='otprequest',
            name='password',
            field=models.CharField(default='4412', max_length=4),
        ),
    ]
