# Generated by Django 5.1.7 on 2025-03-28 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medstore', '0001_initial'),
        ('sort', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('value', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('meta', models.TextField(blank=True, max_length=400)),
                ('amount', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FloatDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='IntDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('meta', models.TextField(max_length=400)),
                ('description', models.TextField()),
                ('org_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('thumbnail', models.ImageField(upload_to='', verbose_name='products/thumbnail/%Y-%m/')),
                ('status', models.CharField(choices=[('P', 'Published'), ('D', 'Draft'), ('A', 'Archived')], default='F', max_length=1)),
                ('is_exist', models.BooleanField(default=False)),
                ('Purchases', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('discount', models.SmallIntegerField(default=0)),
                ('categories', models.ManyToManyField(to='sort.category')),
                ('detailes', models.ManyToManyField(to='products.detail')),
                ('discount_group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.discountgroup')),
                ('float_detailes', models.ManyToManyField(to='products.floatdetail')),
                ('images', models.ManyToManyField(to='medstore.image')),
                ('int_details', models.ManyToManyField(to='products.intdetail')),
                ('tags', models.ManyToManyField(to='sort.tag')),
                ('videos', models.ManyToManyField(to='medstore.video')),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('products', models.ManyToManyField(to='products.product')),
            ],
        ),
    ]
